import { Context_Provider1, context_Value1 } from "@/contexts/context1"
import { Inter } from "next/font/google"

export const metadata = {
  title: 'User Panel',
  description: 'Generated by UCBDev',
  viewport: 'width=device-width, initial-scale=1.0',
  keywords: 'nextjs, UCB, UCBDev',
  themeColor: '#FF0000'
  }
  const inter = Inter({ subsets: ['latin'] })
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
          <body className={inter.className}>{children}</body>
      </html>
    )
  }