import Common_Header from "@/components/common_header/common_header";
import Mobile_Header from "@/components/mobile_header/mobile_header";
import { Context_Provider1, context_Value1 } from "@/contexts/context1";
import { Inter } from "next/font/google";

export const metadata = {
  title: "User Panel",
  description: "Generated by UCBDev",
  viewport: "width=device-width, initial-scale=1.0",
  keywords: "nextjs, UCB, UCBDev",
  themeColor: "#FF0000",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-24 gap-2">
          <Common_Header classes="hidden lg:block" />
          <Mobile_Header classes="block lg:hidden" />
          <div className="col-start-2 col-end-24">{children}</div>
          <div className="col-start-2 col-end-24">This is bottom</div>
        </div>
      </body>
    </html>
  );
}
