import { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by UCBDev",
  viewport: "width=device-width, initial-scale=1.0",
  keywords: "nextjs, UCB, UCBDev",
  themeColor: "#0000FF",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
