import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by UCBDev",
  viewport: "width=device-width, initial-scale=1.0",
  keywords: "nextjs, UCB, UCBDev",
  themeColor: "#0000FF",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
